### ISSUE TITLE
No such property: val for class: com.javagen.schema.kotlin.KotlinJacksonCallback

### ISSUE THREAD

**Issue by zuda-ng** [reaster/schema-gen#3]
https://github.com/reaster/schema-gen/blob/443a222015bc1c0ac4595264b61a659d2d25fe99/src/main/groovy/com/javagen/schema/kotlin/KotlinJacksonCallback.groovy#L188

hi folks,
check with you do we have a typo here?

 value instead of val

**Comment by reaster** [comment]
Fixed. Thanks for the feedback.

**Comment by 0us** [comment]
I am still experiencing this problem on version 0.9.1. Have you not released a version with this fix, or is there a newer version i am missing?

**Comment by k77450** [comment]
I am also hitting this bug and can't find a newer release than 0.9.1 from january 2018.
Could you release a new version?
